### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by haxhaam** [salman-bhai/WhatsApp-Web#6]
Hi salman bhai i hope you will be fine. I just want a little work flow(documentation) of this code. I have some ideas so that i can contribute and we can make it a better tool for world.

**Comment by sbshah97** [comment]
Totally awesome! 

Firstly what all documentation do you want to add?
Secondly tell me about your ideas? We can continue the discussion on this thread hi!

**Comment by haxhaam** [comment]
it is difficult for a newbie to run this script. Please do comment your code or write a document for a newbie so that he/she can run the program smoothly without any problem.

**Comment by sbshah97** [comment]
Alright I'll do that!

**Comment by haxhaam** [comment]
Thank You bro.

**Comment by sbshah97** [comment]
@haxhaam kindly check #8 Is there anything else that you'd like to have as part of a Beginner's Guide. I've updated only the README.md for now! Please do let me know in case there are any Issues
