### ISSUE TITLE
chrome web driver issue

### ISSUE THREAD

**Issue by fadifubbu** [salman-bhai/WhatsApp-Web#7]
from: too many arguments
from: too many arguments
from: too many arguments
./wa.py: line 10: syntax error near unexpected token `('
./wa.py: line 10: `d = webdriver.Chrome('home/Whatsapp-Web/chromedriver')

**Comment by sbshah97** [comment]
Hi, yeah need to change that line from Absolute Path to relative Path! Do you mind forking and opening up a PR while referencing this Issue?

**Comment by fadifubbu** [comment]
I did provide relative path but getting same error I can provide you screen shot you if you want

**Comment by sbshah97** [comment]
Yes please attach a screenshot. Helps better!

**Comment by fadifubbu** [comment]
![salman](https://cloud.githubusercontent.com/assets/18578626/26356228/d33b8bb2-3fe4-11e7-87d9-6dd0cd564915.png)

**Comment by sbshah97** [comment]
Also try removing that space in the line, between Chrome and the bracket.

**Comment by sbshah97** [comment]
That's possibly where the error is coming from!

**Comment by fadifubbu** [comment]
previous error is resolved lib was missing 
web.whatsapp.com is open in back ground my account already scanned to it when I execute it opens up separate window where it goes on web.whatsapp.com should I scan on new opened tab ?

**Comment by fadifubbu** [comment]
/usr/bin/python2.7 /opt/pycharm-community-2017.1.2/helpers/pydev/pydevd.py --multiproc --qt-support --client 127.0.0.1 --port 45907 --file /home/grandpa/Downloads/WhatsApp-Web-master/wa.py
warning: Debugger speedups using cython not found. Run '"/usr/bin/python2.7" "/opt/pycharm-community-2017.1.2/helpers/pydev/setup_cython.py" build_ext --inplace' to build.
Connected to pydev debugger (build 171.4249.47)
pydev debugger: process 6021 is connecting

#

**Comment by sbshah97** [comment]
Hi, check out #8 Try going through those instructions and let me know if you face any problem even after that?
